runtime: python27
api_version: 1
threadsafe: true

#libraries:
#- name: ssl
#  version: latest

libraries:
- name: ssl
  version: latest
- name: enum
  version: latest
- name: grpcio
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /(.*\.css)
  static_files: static/\1
  upload: static/.*\.css
- url: /(.*\.js)
  static_files: static/\1
  upload: static/.*\.js
- url: /.*
  script: main.app
- url: /translate
  script: main.app
- url: /detect
  script: main.app
